CREATE DATABASE db_mii2an;

USE db_mii2an;

CREATE TABLE CLIENTES (
	ID_CLIENTE INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(70) NOT NULL,
    CPF CHAR(11) UNIQUE NOT NULL,
    SENHA CHAR(8) NOT NULL,
    CONFIRMA_SENHA CHAR(8) NOT NULL
);

DESCRIBE CLIENTES;